### ISSUE TITLE
Sane permission defaults for administrator commands

### ISSUE THREAD

**Issue by Astrea49** [Firefly042/ultimate-assistant-pycord#16]
## Is your feature request related to a problem? Please describe
Currently, the bot basically requires new users to invite the bot and *immediately* set permissions for admin commands before anyone can use them. This is very, *VERY* risky - chances are, a new inviter will not be able to do this in time for a malicious actor to use the administrative commands as they see fit.

Furthermore, Discord and Pycord have a built-in solution to at least set default permissions for commands and groups when they join a server. I think that could be used here.

## Describe the solution you'd like
```python
group = SlashCommandGroup(default_member_permissions=discord.Permissions.manage_guild, ...)
```

## Describe alternatives you've considered
Rushing to add in permissions yourself, or not inviting anyone before fully setting up the bot. Neither of which is exactly ideal, though.

## Additional context
Heads up: I'm going to be doing a *lot* of issues and PRs most likely 😅.

**Comment by Firefly042** [comment]
This is either a recent addition to pycord or I am blind. It should be possible to set them to `discord.Permissions.administrator` for the highest security

**Comment by Firefly042** [comment]
```py
announcements = SlashCommandGroup("announcements", "Automated posting",
    default_member_permissions=discord.Permissions.[administrator|manage_guild], ...)
```
Yields `AttributeError: 'flag_value' object has no attribute 'value'`.

I recall using something like this while trying out the library, but it seems it was phased out of the library with permissionsv2 and didn't really accomplish the issue of admin limitation (not to mention that administrators sometimes want to assign a lower-permissioned mod role)

```py
from discord.commands import permissions
...
group = SlashCommandGroup("name", "Description",
    permissions=[permissions.CommandPermission(**perm_arguments)], ...)
```

There was a rather ugly workaround that I had at one point. It was effective in discord.py but seems pretty contentious at this point in pycord. It didn't prevent non-administrators from using a command, but it wouldn't respond to them either. I think it would also forbid administrators from adding non-admin roles to their mod teams.
```py
@groupname.command(...)
@commands.permissions(administrator=True)
async def...
```

If the proposed solution can be made to work, that would be ideal. The next best option is probably the one demonstrated in the third code snippet (though it's pretty bad).

**Comment by Astrea49** [comment]
I'll have to look into it - I'll admit that I'm not very familiar with Pycord 😅.

I doubt the last way is fully possible - subcommands in general can't have their own permissions thanks to Discord being Discord (and also because they're really just fancy options under the hood). But I think it's possible to make something happen.

**Comment by Astrea49** [comment]
Alright, after some playing around, I have a solution:

```python
group = SlashCommandGroup(..., default_member_permissions=discord.Permissions(administrator=True), guild_only=True)
```

This limits the entire group and its subcommands to only administrators by default when the bot joins the server. A server administrator can edit it from there as they see fit.

`guild_only` also needs to be provided here because, well, Discord once again doesn't actually allow it to be set per subcommand.

**Comment by Firefly042** [comment]
Should be all set with #37
