### ISSUE TITLE
Don't remove pycache on exit

### ISSUE THREAD

**Issue by Astrea49** [Firefly042/ultimate-assistant-pycord#26]
## Is your feature request related to a problem? Please describe
Python automatically creates a cache for files when they are run for the first time so that they can be run faster the second+ time around. This is a nice speedup and has little, if no, downsides.

For some reason, Ultimate Assistant removes them upon the program ending. This is both unnecessary, as the files are only helpful and do not get picked up thanks to the `.gitignore` (ideally, at least it won't with my `.gitignore` PR), but also means extra operations have to be done when booting up from scratch (and deleting files has some cost, too).

## Describe the solution you'd like
Remove the removal of those files on program exit.

## Describe alternatives you've considered
N/A... besides I guess leaving the code as is.

## Additional context
Let me know if you have concerns over removing it or if there's a valid reason to delete the caches - I *think* this may be worth talking about.

**Comment by Firefly042** [comment]
Addressed by #24
